docker-compose-local-build.yaml, docker-compose.yaml
This file can be used to bring up a container by running `docker-compose up -d -f ./docker-compose.yaml`.
=> Added docker-compose.yaml

README.md
Small change to describe environment variables that are read by archivy.
=> Add "Configuration" section

setup.py
This one looks redundant. I guess this was added on mistake.
=> Remove redundant comment on setup.py

archivy/static/main.css
Seems like the indentation is unconventional. Feel free to close if that was intentional!
=> Fix indent in css

archivy/templates/home.html
This was a feature I wanted, so I just went ahead and made it :)
=> Add expand/collapse toggle functionality

archivy/models.py
This also allows saving pages with no title.
=> improve error handling in process_bookmark_url

archivy/__init__.py, archivy/check_changes.py, archivy/extensions.py, archivy/search.py
- some refactoring in the search functionality was needed to run everything in
an app context
- logging level set to INFO at app instantiation
=> use flask logger instead of `print` for loging messages

Dockerfile, container-structure-test.yaml, docker-compose-with-elasticsearch.yml, docker-compose.yml
Updated the version number of archivy to `0.0.8` in:
- `Dockerfile`
- `container-structure-test.yaml`
- `docker-compose.yml`
- `docker-compose-with-elasticsearch.yml`
=> Updated archivy version to 0.0.8

Dockerfile, container-structure-test.yaml, docker-compose-with-elasticsearch.yml, docker-compose.yml, healthcheck.sh
Added the `HEALTHCHECK` directive to `Dockerfile`. To that end, I've
also added the `healthcheck.sh` which is used by the Docker daemon to
check if the container is healthy i.e up and running.
Have bumped up the version of Archivy in the container to `0.1.0`. These
changes have been made to `container-structure-test.yaml`,
`docker-compose.yml`, `docker-compose-with-elasticsearch.yml`, and
`Dockerfile`.
=> Added healthcheck to Dockerfile. Bumped up version.

archivy/config.py, archivy/search.py, archivy/static/main.css, archivy/static/mvp.css, archivy/templates/base.html
Added dark mode for the application.
There is a button in the right corner which gives the option to toggle from dark mode to white mode.
Fixed #89
=> Dark theme

.github/workflows/build-docker-on-push-master.yml, .github/workflows/build-docker-on-release.yml
There was an error in the actions file which builds the image based on code in the `master` branch. One of the jobs incorrectly referred to `Dockerfile` instead of `Dockerfile.source`. Fixed this.
Have updated the `docker buildx` step to the official action.
=> Error fixes and improvements in Github Actions files

archivy/search.py, archivy/templates/dataobjs/new.html, archivy/templates/home.html
Improves the speed of the pandoc rendering of search results by chunking everything at once and executing the conversion markdown -> pandoc at once.
=> improve speed of ES by rendering everything on the backend

README.md, archivy/__init__.py, archivy/cli.py, archivy/helpers.py, archivy/models.py, conftest.py, docs/index.md, docs/install.md, tests/unit/test_cli.py
Fixes #132.
@srevinsaju could you check this out?
Thanks!
=> Add command to create admin user

archivy/click_web/resources/cmd_exec.py, archivy/click_web/resources/index.py, archivy/click_web/resources/input_fields.py, archivy/click_web/web_click_types.py, archivy/templates/click_web/show_tree.html, docs/plugins.md, docs/reference/web_inputs.md, mkdocs.yml
Fixes https://github.com/archivy/archivy/issues/143.
This PR also:
- rectifies the message on the /plugins page
- adds a password input type so people can use passwords as options for plugins
- documents ^
=> Enhance plugins and web interface

archivy/api.py, archivy/check_changes.py, archivy/data.py, archivy/models.py, archivy/routes.py, archivy/static/main.css, archivy/templates/base.html, archivy/templates/dataobjs/show.html, archivy/templates/home.html, tests/integration/test_api.py
Fixes #33 
Adds inline markdown editor using https://github.com/Ionaru/easy-markdown-editor.
Improvements:
Problems:
Some pandoc markdown features like math equations are not previewed in the right manner.
Demo:
=> Inline editor

.github/workflows/flake.yml, archivy/__init__.py, archivy/api.py, archivy/check_changes.py, archivy/cli.py, archivy/config.py, archivy/data.py, archivy/helpers.py, archivy/models.py, archivy/routes.py, config.yml, conftest.py, docs/config.md, docs/editing.md, docs/install.md, docs/setup-search.md, docs/usage.md, tests/unit/test_cli.py
Enhance setup process with addition of a new `init` command that acts as a setup wizard. Also enhances setup process with a `config.yml` file to replace ENV variables. Fixes #107
=> ADD: init command + config.yml

archivy/cli.py
It is enough with the `cls` parameter as `FlaskGroup`.
=> Remove unnecessary code from cli

archivy/static/accessibility.css, archivy/templates/dataobjs/show.html
Added screenreader support that fixes #205
=> Added screenreader support

archivy/templates/dataobjs/show.html, archivy/templates/home.html, docs/CONTRIBUTING.md
=> Add confirmation modal for item and folder deletion + doc update

archivy/__init__.py, archivy/api.py, archivy/data.py, archivy/routes.py, archivy/templates/dataobjs/show.html, conftest.py, tests/integration/test_api.py
Stores image in a `images` subdirectory inside the user directory.
=> ADD: Image upload functionality

.gitignore, archivy/api.py, archivy/data.py, archivy/forms.py, archivy/routes.py, archivy/static/main.css, archivy/templates/dataobjs/show.html, tests/functional/test_routes.py, tests/integration/test_api.py
- Rename `update_item` -> `update_item_md`
- Add `api.update_dataobj_frontmatter`
- Add `data.update_item_frontmatter`. This routine only changes the elements that were supplied to it. This way it can be also used to change date, type and tags.
- Remove `title` from `show.html` because we already have `dataobj['title']`
- Adapt the CSS of the frontmatter a bit so that everything is aligned on the left.
=> Editing the title in the front matter

README.md
Changed "at" to "to" in the Community section
=> changed at to to

archivy/static/main.css
=> [#245] Set width for post-title-form input#title.

archivy/routes.py, archivy/search.py, archivy/tags.py, archivy/templates/dataobjs/show.html, tests/functional/test_routes.py
Uses rip grep to reintegrate frontmatter tags in core parts of the UI, but faster than by getting all items.
=> Improve frontmatter tags

archivy/models.py, conftest.py, requirements.txt, tests/functional/test_routes.py
Uses [python-readability](https://github.com/buriy/python-readability) for better scraping.
Notably articles saved with this method have much less noise / only post content is saved.
=> Better scraping

archivy/templates/dataobjs/show.html, docs/editing.md
=> Auto Note Link Creation

archivy/config.py, archivy/routes.py, archivy/templates/dataobjs/show.html
Can be useful generally, and will help me with my Archivy-Espial (https://github.com/Uzay-G/espial) integration
=> Allow customization of note / bookmark show page through JS

archivy/routes.py, archivy/static/main.css, archivy/templates/home.html
A tag cloud is shown above the list of directories and notes
=> Tag cloud per folder

archivy/api.py, archivy/data.py, archivy/models.py, archivy/routes.py, archivy/templates/home.html
No design for now, suggestions welcome.
=> Create panel for recently modified pages in a given directory
