archivy/archivy

requirements.txt, start.sh
The requirements.txt doesn't work due to some extraneous output.
Added a simple fix to get start.sh working a bit better as well. Can .flaskenv be checked into the repo? Is always set to archivy right?
=> A few simple fixes for getting this up and running

start.sh
Have changed shebang from `#!/bin/env` to `#!/usr/bin/env`. On certain Docker images(like Debian Buster Slim), `#!/bin/env` isn't set.
=> Changed shebang in `start.sh`

start.sh
Changed `flask run` command by adding the `--host=0.0.0.0` in order to bind to all interfaces. Previously, it would bind to localhost(127.0.0.1) which would cause issues with connecting to the service when containerised. For detailed information on why this happens, refer to this [link](https://pythonspeed.com/articles/docker-connection-refused/).
=> Updated `flask run` command in `start.sh` file

local-build.Dockerfile
This Dockerfile is better for building and testing locally as it does not download the source code. Instead, it copies the code from the host. Therefore, this Dockerfile needs to be present in the root of the repository as a pre-requisite to building the container image.
=> Added local-build.Dockerfile

Dockerfile, entrypoint.sh, local-build.Dockerfile
Have added `entrypoint.sh` which takes care of setting and overriding environment variable(like the ones in `.flaskenv`) as per user-provided values. People using the docker image can now provide their own values for
- `FLASK_DEBUG`
- `ELASTICSEARCH_ENABLED`
- `ELASTICSEARCH_URL`
and if they do not, default values will be set automatically.
`Dockerfile` and `local-build.Dockerfile` have been modified to make use of `entrypoint.sh`.
=> Added `entrypoint.sh`, modified `Dockerfile` and `local-build.Dockerfile` to use `entrypoint.sh`.

start.sh
* Add some checks before attempting to run Archivy
* Only source venv/bin/activate if user currently not in a virtual environment already
* Check if python3 is installed and on PATH
* Fail the script, if any command in the shell script exited with a non-zero exit code
* Automatically create a venv if it was not found; and install packages using pip
btw, amazing project! 483 stargazers already!!! :tada:
Looking forward for a built-in Markdown editor in future :+1:  (Idk, if thats too much to ask!!)
=> Improve start.sh

archivy/__init__.py, archivy/extensions.py
- use ES built-in health report instead of platform-dependant subprocess call
- print user-friendly error messages instead of running subprocess commands
with sudo
=> improve error handling for elasticsearch

.github/workflows/pytest.yml, archivy/data.py, archivy/extensions.py, archivy/models.py, archivy/routes.py, conftest.py, requirements-tests.txt, tests/integration/test_pocket.py, tests/unit/test_models.py
Add integrations test for the pocket import, and several improvements for future testing.
New fixtures:
- `test_app` for setting up a temporary database for each test
- `client` for setting up  test client to test routes
- `mocked_responses` for setting up `responses`-based mocked HTTP calls (see below) 
Other changes:
- add `requirements-tests.txt` for test dependencies (`pytest` and `responses`)
- refactoring in `data.py` and `models.py` to allow changing the data directory at runtime
- fix possible bug in `parse_pocket`
I'm using https://pypi.org/project/responses/ for mocking out requests calls in the pocket route. This can be confusing because the test client does not use `requests` (see https://werkzeug.palletsprojects.com/en/1.0.x/test/#werkzeug.test.Client). So, in my test, only …
=> Improve testing and add integration test for pocket

archivy/models.py
- BeautifulSoup was throwing a `GuessedAtParserWarning` because the parser was
not explicitely specified
=> explicitely specifiy parser to remove beautiful soup warning

Dockerfile, container-structure-test.yaml, docker-compose-with-elasticsearch.yml, docker-compose.yml, entrypoint.sh
Changed the login shell of the `archivy` user in the container from
`/bin/nologin` to `/sbin/nologin` which the correct path.
Added tests to `container-structure-test.yaml` for checking the user
which is running inside the container, ther user's group, and their
login shell.
Denied linux capabilities to `archivy` and `elasticsearch` containers in
the compose files. For `elasticsearch`, only `SYS_CHROOT` and `SETUID`
capabilities are granted. By default, all capabilties are dropped first.
This prevents processes from having more than necessary capabilities
inside the container.
Changed image tag to `0.0.7` in `docker-compose.yml`.
Removed author's name from `entrypoint.sh`.
=> Security-related changes

.github/workflows/build-docker-on-push-master.yml, .github/workflows/build-docker-on-release.yml
Have fixed the error in `build-docker-on-push-master.yml` and `build-docker-on-release.yml`, which was that the job `dockerBuildPush` was depending on the job `ContainerTestScan`. The name of this job was actually `ContainerTestAndScan`.
Have removed the `trigger on pull request to master branch` condition in `build-docker-on-push-master.yml` as it would result in images built with unmerged and unapproved code.
Also changed the version of the `checkout` action to `v2` in both files.
=> Fixed errors in `build-docker-on-push-master.yml` and `build-docker-on-release.yml`.

.github/workflows/build-docker-on-push-master.yml, .github/workflows/build-docker-on-release.yml
In files `build-docker-on-push-master.yml` and `build-docker-on-release.yml`, the `--build-arg` value needs to be in
the form of `KEY=VALUE`. Instead, it was `KEY VALUE`. Have fixed this.
=> Fixed errors in docker-related actions files

archivy/__init__.py
the token_hex is comparatively vulnerable as it does not include
non-alphanumeric characters. token_urlsafe would help to provide a safer
password for the administrator
=> feat: Use safer autogenerated passwords

.github/workflows/build-docker-on-push-master.yml, .github/workflows/build-docker-on-release.yml, setup.py
In `build-docker-on-push-master.yml`, the job `buildPushUntested` was referring to a variable `tag_name` instead of `image_tag`, which led to images being pushed with the tag `untested-`. This has been fixed.
In `build-docker-on-release.yml`, the conditions which trigger the run were `on publish of release`. This wasn't getting triggered when tags were being pushed, which is needed. Have added a condition `on push of tags`.
Also, there's an error in the linting step(`Hadolint`). This will be fixed in the `docker` branch.
=> Fixed errors in Actions files

archivy/static/main.css
Added a rule to invert the colors of the edit profile button at the home page, as means of improving contrast in the Dark Theme.
(The edit profile button is an SVG located at the left top corner of the screen, currently acts as a button)
_Before:_
_After:_
=> DarkTheme: correction for the contrast of the Edit Profile button

archivy/__init__.py, archivy/api.py, archivy/check_changes.py, archivy/cli.py, archivy/config.py, archivy/data.py, archivy/helpers.py, archivy/models.py, archivy/routes.py, archivy/search.py, archivy/static/main.css, docs/config.md, docs/plugins.md, docs/reference/architecture.md, docs/setup-search.md, docs/usage.md, tests/unit/test_cli.py
This PR introduces several changes:
- Renames `ELASTICSEARCH_CONF` to `SEARCH_CONF` for future integration with other search engines #13
- Add `enable_watcher` key to ^ above config object for whether or not to run the watcher that syncs file changes to ES.
- Watcher used to check when there was a new file in the data directory, and if unformatted, would convert it to archivy format. This no longer exists, and instead a `format` and `unformat` command have been added to the cli.
- Addition of `index` command to index all files for ES.
=> Changes to the watcher and how archivy converts unformatted files

archivy/cli.py
Now its possible to run archivy directly from source
without installing archivy first by using
$ python3 -m archivy.cli --help
This can help test multiple versions of archivy without
creating multiple virtualenv's.
=> fix: expose __main__ on archivy.cli

README.md
It looks like the logo has more priority than the content. This blocks important information. A user would likely need to know first about archivy, before the license.
Content first, then license.
Moved archivy's logo license after archivy's license itself in a new section
=> docs: move license to logo below content

archivy/api.py, archivy/data.py, tests/integration/test_api.py
At the moment it is still possible to delete directories using relatives path. For example sending a request with the path `../../../../../../../../bin` would delete the /bin folder if you have the permission
=> Fix possible removal of directories with path traversal

.github/workflows/black.yml, archivy/__init__.py, archivy/api.py, archivy/cli.py, archivy/click_web/__init__.py, archivy/click_web/resources/cmd_exec.py, archivy/click_web/resources/cmd_form.py, archivy/click_web/resources/index.py, archivy/click_web/resources/input_fields.py, archivy/click_web/web_click_types.py, archivy/config.py, archivy/data.py, archivy/helpers.py, archivy/models.py, archivy/routes.py, archivy/search.py, conftest.py, docs/example-plugin/archivy_extra_metadata/__init__.py, docs/example-plugin/setup.py, setup.py, tests/functional/test_plugins.py, tests/functional/test_routes.py, tests/integration/test_api.py, tests/test_click_web.py, tests/test_plugin/plugin.py, tests/test_plugin/setup.py, tests/unit/test_cli.py, tests/unit/test_click_web.py, tests/unit/test_hooks.py, tests/unit/test_models.py
`flake8` is old and cumbersome, its painful, and a waste of time. The [PSF](https://en.wikipedia.org/wiki/Python_Software_Foundation) has created, and recommends new users to use the `black` code style, which is simple and ubobstrusive. 
The benefits of using `black` is that,
* it has an autolinter,
* It keeps a balance between readability and line limits
* The code looks exactly the same, despite how many times your run the linter on it. 
We can even attach a GitHub Action to automatically lint new user's pull requests, but I guess, I will leave that for discussion.
I have seen some projects adding `.git/hooks/pre-commit`, which runs the black linter before every commit. So all commits are neater than ever.
PS: the change from `'` to `"` is to signify i18n, as convention. `black` …
=> Move to the 'black' code style.

archivy/config.py, archivy/data.py, archivy/models.py, docs/config.md, tests/unit/test_models.py
This implements a new config option, inside `SCRAPING_CONF["save_images"]` where images called in downloaded webpages are stored locally. I decided to set this to False by default.
=> Improvements to image upload

archivy/data.py, archivy/forms.py, archivy/routes.py, archivy/static/main.css, archivy/templates/dataobjs/show.html, tests/functional/test_routes.py
Could also be used to address this issue https://github.com/archivy/archivy/issues/223.
=> Add a form to move notes to other folders.

archivy/api.py, archivy/config.py, archivy/routes.py, archivy/templates/dataobjs/show.html, docs/config.md, docs/editing.md, tests/functional/test_routes.py, tests/integration/test_api.py
Adds two related imrpovements:
- a new "bookmark" icon is available which allows you to scrape a url you've selected with your cursor and replace it with a locally archived version.
- You can configure a default bookmarks dir to save bookmarks if the `path` is omitted, instead of having them encumber your root dir.
=> Editor improvements to save bookmark from editor + new DEFAULT_BOOKMARKS_DIR option

archivy/config.py, archivy/data.py, archivy/routes.py, archivy/templates/base.html, docs/config.md, tests/functional/test_routes.py
This PR adresses https://github.com/archivy/archivy/issues/228 and adds the following section to `config.yml`:
```
THEME_CONF:
use_custom_css: true
custom_css: mytheme.css
```
allowing to serve a custom css file from USER_DIR/css.
=> Allow loading custom css from USER_DIR/css

archivy/config.py, archivy/templates/base.html, archivy/templates/bookmarklet.html, archivy/templates/dataobjs/new.html, archivy/templates/users/edit.html, archivy/templates/users/login.html, docs/config.md
Allow a user to override the normal application page title and headers via a configuration variable. Summary of changes:
- added SITE_TITLE config variable with default "Archivy"
- render SITE_TITLE in templates
- described SITE_TITLE in docs/config.md
Note that the default value for SITE_TITLE is included in the `config.yml` generated by the `archivy init` CLI command, and no changes have been made to allow users to set the value interactively via this command (possible future improvement).
=> Allow override of "Archivy" for site title and page headings

archivy/config.py, archivy/templates/dataobjs/show.html, archivy/templates/markdown-parser.html, docs/config.md
Includes the possibility to set up the markdown-it settings in the archivy configuration (https://github.com/archivy/archivy/issues/209).
I also prettified the javascript a bit.
=> Editor config

archivy/cli.py, archivy/helpers.py, tests/unit/test_cli.py
Using the `archivy plugin-new <name>` can now set up a directory structure making it easier to create a plugin for archivy.
Implements #152
=> Add helper command to generate plugin directory with structure

archivy/config.py
Allows overriding default internal dir, instead of
the path chosen by appdirs
Example:
```
(venv) clemux@charlotte:~/dev/archivy$ ARCHIVY_INTERNAL_DIR_PATH=/tmp/ archivy init
This is the archivy installation initialization wizard.
Enter the full path of the directory where you'd like us to store data. [/home/clemux/dev/archivy]: /tmp/archivy
Would you like to enable search on your knowledge base contents? [y/N]: n
Would you like to create a new admin user? [y/N]: n
Host [localhost (127.0.0.1)]: 
Config successfully created at /tmp/config.yml
```
=> WIP: feat: add ARCHIVY_INTERNAL_DIR_PATH env variable

archivy/config.py, archivy/templates/dataobjs/show.html
If you don't mind, I'd like to disable spell-check.
Right now, we have the editor configuration that is actually a markdown-parser configuration. We could incorporate this change into a new config object that goes
```
rendering = {
"markdown-parser": what-we-already-have,
"editor": things like this
}
```
Sorry for the git hick-up
=> Disable spell check

archivy/data.py
on Fedora 35 Silverblue, /home is a symlink to /var/home and hence
archivy has trouble trying to figure out if data directory is relative
to query_dir.
Fixes the following traceback
```
[2022-02-04 12:35:35,253] ERROR in app: Exception on /login [GET]
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
return …
```
=> fix: check is_relative_to based on resolved paths

.github/workflows/codecov.yml, archivy/click_web/resources/cmd_exec.py, archivy/data.py, archivy/models.py, archivy/routes.py, archivy/tags.py, requirements.txt, tests/functional/test_routes.py, tests/integration/test_api.py
=> fix RAM usage and clean stuff up
